name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run my repository
        uses: actions/checkout@v4

        #Building my container
      - name: build container
        run: docker compose build

        # Run my container
      - name: run the container
        run: docker compose up -d

        # checking work the container
      - name: check the container
        run: docker compose ps -a

        # show backend logs
      - name: show backend logs
        run: docker compose logs back

        # health check backend
      - name: check backend
        run: curl -f http://localhost:8000/health

        # health check bd
      - name: check bd
        run: docker compose exec database pg_isready -U admin
