name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run my repository
        uses: actions/checkout@v4
      - name: build container
        run: docker compose build
      - name: run the container
        run: docker compose up
      - name: check the container
        run: docker compose ps -a
